"""Replace LockedMeal with MealPlan model

Revision ID: 30bf8caeb657
Revises: cd1dfba2a05d
Create Date: 2025-06-27 21:23:48.523877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bf8caeb657'
down_revision = 'cd1dfba2a05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locked_meal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locked_meal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.VARCHAR(length=10), nullable=False),
    sa.Column('meal_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('manual_text', sa.VARCHAR(length=200), nullable=True),
    sa.Column('is_manual', sa.BOOLEAN(), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), nullable=True),
    sa.Column('lock_type', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'meal_type', name='unique_day_meal')
    )
    # ### end Alembic commands ###
