"""Add is_admin column to User model

Revision ID: cd1dfba2a05d
Revises: 
Create Date: 2025-06-23 20:35:49.773579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1dfba2a05d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # First add the column as nullable
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute('UPDATE "user" SET is_admin = 0')
    
    # Now alter the column to be non-nullable
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin', existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
